name: ClawTriage Issue Triage
description: Triage a single GitHub issue — semantic dedup, quality scoring, VISION.md alignment

inputs:
  github-token:
    description: GitHub token with issues write permission
    required: true
  openai-api-key:
    description: OpenAI API key for embeddings
    required: true
  anthropic-api-key:
    description: Anthropic API key for vision alignment
    required: true
  issue-number:
    description: Issue number to triage
    required: true
  repo:
    description: Target repo (owner/repo)
    required: false
    default: ${{ github.repository }}
  similarity-threshold:
    description: Cosine similarity threshold (0-1)
    required: false
    default: "0.82"
  post-comment:
    description: Post triage comment on the issue
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ github.action_path }}

    - name: Build
      shell: bash
      run: pnpm build
      working-directory: ${{ github.action_path }}

    - name: Restore issue embedding cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.clawtriage-issue-cache.json
        key: clawtriage-issue-${{ inputs.repo }}-${{ github.run_id }}
        restore-keys: |
          clawtriage-issue-${{ inputs.repo }}-

    - name: Run ClawTriage Issue Triage
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        CLAWTRIAGE_REPO: ${{ inputs.repo }}
        SIMILARITY_THRESHOLD: ${{ inputs.similarity-threshold }}
        ISSUE_CACHE_PATH: ${{ github.workspace }}/.clawtriage-issue-cache.json
        POST_COMMENT: ${{ inputs.post-comment }}
      run: node dist/index.js issue-triage ${{ inputs.issue-number }}
