name: ClawTriage
description: AI-powered PR triage — semantic deduplication, quality scoring, VISION.md alignment
author: RogGriff

inputs:
  github-token:
    description: GitHub token with pull-requests write permission
    required: true
  openai-api-key:
    description: OpenAI API key for text-embedding-3-small
    required: true
  anthropic-api-key:
    description: Anthropic API key for claude-haiku-4-5-20251001
    required: true
  repo:
    description: Target repo in owner/repo format
    required: false
    default: ${{ github.repository }}
  pr-number:
    description: PR number to triage
    required: true
  similarity-threshold:
    description: Cosine similarity threshold (0-1)
    required: false
    default: "0.82"
  post-comment:
    description: If true, post triage comment to the PR
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ github.action_path }}

    - name: Build
      shell: bash
      run: pnpm build
      working-directory: ${{ github.action_path }}

    - name: Restore embedding cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.clawtriage-cache.json
        key: clawtriage-${{ inputs.repo }}-${{ github.run_id }}
        restore-keys: |
          clawtriage-${{ inputs.repo }}-

    - name: Run ClawTriage
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        CLAWTRIAGE_REPO: ${{ inputs.repo }}
        SIMILARITY_THRESHOLD: ${{ inputs.similarity-threshold }}
        CACHE_PATH: ${{ github.workspace }}/.clawtriage-cache.json
        POST_COMMENT: ${{ inputs.post-comment }}
      run: node dist/index.js triage ${{ inputs.pr-number }}
