import type { BatchResult, BatchTriageEntry, DuplicateCluster } from "./types.js";

export function buildSummaryIssue(result: BatchResult): { title: string; body: string } {
  const title = `ClawTriage Batch Report — ${result.repo} — ${result.timestamp.split("T")[0]}`;
  const { stats, clusters, entries } = result;
  const lines: string[] = [];

  lines.push(`## ClawTriage Batch Triage Report\n`);
  lines.push(`**Repository:** ${result.repo}`);
  lines.push(`**PRs analyzed:** ${result.totalPRs}`);
  lines.push(`**Run date:** ${result.timestamp}\n`);

  // Summary table
  lines.push(`### Summary\n`);
  lines.push(`| Metric | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| Total PRs | ${stats.totalPRs} |`);
  lines.push(`| Duplicate clusters | ${stats.duplicateClusters} (${stats.duplicatePRs} PRs) |`);
  lines.push(`| Avg quality score | ${stats.avgQuality}/10 |`);
  lines.push(`| Vision: fits | ${stats.visionFits} |`);
  lines.push(`| Vision: strays | ${stats.visionStrays} |`);
  lines.push(`| Vision: rejects | ${stats.visionRejects} |`);
  lines.push(``);

  // Duplicate clusters
  if (clusters.length > 0) {
    lines.push(`### Duplicate Clusters\n`);
    const entryMap = new Map<number, BatchTriageEntry>();
    for (const e of entries) entryMap.set(e.prNumber, e);

    clusters.forEach((cluster: DuplicateCluster, i: number) => {
      lines.push(
        `**Cluster ${i + 1}** (avg similarity: ${Math.round(cluster.avgSimilarity * 100)}%) — Canonical: #${cluster.canonical}`,
      );
      for (const member of cluster.members) {
        const entry = entryMap.get(member);
        const memberTitle = entry ? entry.title : `PR #${member}`;
        lines.push(`- #${member}: ${memberTitle}`);
      }
      lines.push(``);
    });
  }

  // Top merge candidates
  const mergeCandidates = entries.filter(
    (e) => e.qualityScore >= 8 && e.visionAlignment === "fits",
  );
  if (mergeCandidates.length > 0) {
    lines.push(`### Top Merge Candidates (quality >= 8, vision fits)\n`);
    lines.push(`| PR | Quality | Title |`);
    lines.push(`|---|---|---|`);
    for (const e of mergeCandidates.sort((a, b) => b.qualityScore - a.qualityScore)) {
      lines.push(`| #${e.prNumber} | ${e.qualityScore}/10 | ${e.title} |`);
    }
    lines.push(``);
  }

  // Needs revision
  const needsRevision = entries.filter((e) => e.qualityScore < 4);
  if (needsRevision.length > 0) {
    lines.push(`### Needs Revision (quality < 4)\n`);
    lines.push(`| PR | Quality | Title |`);
    lines.push(`|---|---|---|`);
    for (const e of needsRevision.sort((a, b) => a.qualityScore - b.qualityScore)) {
      lines.push(`| #${e.prNumber} | ${e.qualityScore}/10 | ${e.title} |`);
    }
    lines.push(``);
  }

  // Vision rejects
  const visionRejects = entries.filter((e) => e.visionAlignment === "rejects");
  if (visionRejects.length > 0) {
    lines.push(`### Vision Rejects\n`);
    lines.push(`| PR | Reason | Title |`);
    lines.push(`|---|---|---|`);
    for (const e of visionRejects) {
      lines.push(`| #${e.prNumber} | ${e.visionReason} | ${e.title} |`);
    }
    lines.push(``);
  }

  // Full triage table
  lines.push(`### Full Triage Table\n`);
  lines.push(`<details>`);
  lines.push(`<summary>All ${entries.length} PRs</summary>\n`);
  lines.push(`| PR | Quality | Vision | Dupes | Action | Title |`);
  lines.push(`|---|---|---|---|---|---|`);
  for (const e of entries) {
    const dupeLabel = e.duplicateCluster !== null ? `Cluster ${e.duplicateCluster + 1}` : "-";
    lines.push(
      `| #${e.prNumber} | ${e.qualityScore} | ${e.visionAlignment} | ${dupeLabel} | ${e.recommendedAction} | ${e.title} |`,
    );
  }
  lines.push(`\n</details>\n`);

  lines.push(`---`);
  lines.push(`*Generated by [ClawTriage](https://github.com/GriffinAtlas/clawtriage) — batch mode*`);

  return { title, body: lines.join("\n") };
}
